export const requests = [
    {
        id: '01',
        fullName: 'Джатдоев Алим Сеит-Алиевич',
        post: 'КВС',
        date: '2024-05-17',
        aviacompany: 'Азимут',
        aviacompany_icon: 'azimut_preview.png',
        airport: 'MRV',
        arrival_title: 'РС№0024358',
        arrival_date: '17.05.2024',
        arrival_time: '13:50',
        departure_title: 'РС№002435',
        departure_date: '19.06.2024',
        departure_time: '14:50',
        status: 'В обработке',
        statusCode: 'processing',
    },
    {
        id: '02',
        fullName: 'Гочияев Руслан Романович',
        post: 'КВС',
        date: '2024-05-18',
        aviacompany: 'S7 airlines',
        aviacompany_icon: 'S7-airlines-preview.png',
        airport: 'MRV',
        arrival_title: 'РС№002435',
        arrival_date: '17.05.2024',
        arrival_time: '13:50',
        departure_title: 'РС№002435',
        departure_date: '17.05.2024',
        departure_time: '13:50',
        status: 'Отменен',
        statusCode: 'cancelled',
    },
    {
        id: '03',
        fullName: 'Уртенов Азамат Заурович',
        post: 'КВС',
        date: '2024-05-18',
        aviacompany: 'Северный ветер',
        aviacompany_icon: 'Северный-ветер-preview.png',
        airport: 'MRV',
        arrival_title: 'РС№002435',
        arrival_date: '17.05.2024',
        arrival_time: '13:50',
        departure_title: 'РС№002435',
        departure_date: '17.05.2024',
        departure_time: '13:50',
        status: 'Готово',
        statusCode: 'done',
    },
]