export const requests = [
    {
        id: '01',
        fullName: 'Иванов Иван Иванович',
        post: 'КВС',
        date: '2024-05-17',
        aviacompany: 'Азимут',
        airport: 'MRV',
        airport_icon: 'azimut_preview.png',
        arrival_title: 'РС№002435',
        arrival_date: '17.05.2024',
        arrival_time: '13.50',
        departure_title: 'РС№002435',
        departure_date: '17.05.2024',
        departure_time: '13.50',
        status: 'В обработке',
        statusCode: 'processing',
    },
    {
        id: '02',
        fullName: 'Иванов Иван Иванович',
        post: 'КВС',
        date: '2024-05-18',
        aviacompany: 'Азимут',
        airport: 'MRV',
        airport_icon: 'azimut_preview.png',
        arrival_title: 'РС№002435',
        arrival_date: '17.05.2024',
        arrival_time: '13.50',
        departure_title: 'РС№002435',
        departure_date: '17.05.2024',
        departure_time: '13.50',
        status: 'В обработке',
        statusCode: 'cancelled',
    },
]